base_params_to_update: 
    max_time_SyID_severe: 18
    days_between_tests: 1
    test_population_fraction: 0.07
    contact_trace_testing_frac: 0.5

   
ntrajectories: 500
time_horizon: 112
param_to_vary: SyID_severe_time_mean
parameter_values: [5,6,7,8,9,10,11,12,13]
