base_params_to_update:
    days_between_tests: 1
    test_population_fraction: 0.07
    contact_trace_testing_frac: 0.5

ntrajectories: 500
time_horizon: 112
param_to_vary: ID_mean_time
parameter_values: [2.75,3,3.25,3.5,3.75,4,4.25]
