base_params_to_update:
    max_time_exposed: 8
    days_between_tests: 1
    test_population_fraction: 0.07
    contact_trace_testing_frac: 0.5

ntrajectories: 500
time_horizon: 112
param_to_vary: E_time_mean
parameter_values: [0,0.5,1,1.5,2,2.5,3,3.5,4]
