_inherit_config: ./fall_nominal.yaml
_scenario_name: Fall Re-Open Additional Ithaca Infections with returning population = 10000

# this parameter specifies prevalence as a percentage
initial_ID_prevalence: 0

# this parameter specifies prevalence as a count
initial_ID_count: 4

# specify prevalence in E as a count
initial_E_count: 6

# reset daily outside infections to 0
daily_outside_infection_p: 0

# specify that this config does use asymptomatic testing
use_asymptomatic_testing: True

# what fraction of positive cases from testing go through contact-tracing
contact_trace_testing_frac: 0.5

# testing parameters
days_between_tests: 1

test_population_fraction: 0.2

test_protocol_QFNR: 0.1
test_protocol_QFPR: 0.001
